language: csharp
mono: none
dotnet: 2.1.103
addons:
    chrome: stable
cache: yarn
before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
    - export PATH="$HOME/.yarn/bin:$PATH"
script:
    - dotnet restore
    - dotnet build
